name: flutter_mpmediaplayer
description: A plugin to interface with MPMediaPlayer on iOS/iPadOS.
version: 0.3.0
homepage: "https://github.com/nrubin29/flutter_mpmediaplayer"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterMpmediaplayerPlugin
